---
kind: pipeline
name: default

steps:
- name: test
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - pwd
  - ls -la
  - docker ps -a
  - docker network ls
  - docker run --rm --network drone_net -v /home/saniar/:/app -w /app golang:1.18.3-buster /bin/bash -c "apt-get update | echo y && apt-get install npm && cd cortex && npm test"

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

# ---
# kind: pipeline
# name: Front auto test //trusted repo

# steps:
# - name: jest_test
#   image: docker 
#   commands:
#   - pwd
#   - ls -la
#   - docker ps -a
#   - docker network ls
#   volumes:
#   - name: unixsocket
#     path: /var/run/docker.socket
#   - name: data
#     path: /tmp/cache/
#   privileged: true

# volumes:
# - name: unixsocket
#   path: /var/run/docker.sock
# - name: data
#   host:
#     path: /home/saniar/

# trigger:
#   event:
#   - push
#   - pull_request
# ---
# kind: pipeline
# name: default

# steps:
# - name: test
#   image: docker
#   volumes:
#   - name: dockersock
#     path: /var/run/docker.sock
#   commands:
#   - docker ps -a

# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock

# ---
# kind: pipeline
# name: default

# steps:
# - name: write
#   image: ubuntu
#   commands:
#   - touch foo.txt
#   - echo "trying some texts" > foo.txt


# - name: read
#   image: ubuntu
#   commands:
#   - cat foo.txt

# steps:
# - name: greeting 
#   commands:
#   - echo hello world
# steps:
# - name: my-docker
#   image: docker
#   commands:
#   - |
    # apt install npm
    # echo check node version
    # node --version
    # echo
    # echo install docker 
    # chmod +x docker-install.sh
    # ./docker-install.sh
    # echo
    # echo check docker version
    # docker --version
    # pwd
    # ls /var/run
    # echo $?
    # docker ps
    # volume:
    # - /var/run/docker.sock:/var/run/docker.sock
  
# trigger:
#   branch:
#   - main